// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
	auth: {
		errors: {
			emailRequired: "Email is required";
			invalidCredentials: "Invalid email or password";
			passwordMismatch: "Passwords don't match";
			passwordRequired: "Password is required";
		};
		login: {
			divider: "or";
			emailLabel: "Email";
			googleButton: "Continue with Google";
			noAccount: "Don't have an account?";
			passwordLabel: "Password";
			signInButton: "Sign In";
			signUpLink: "Sign up";
			subtitle: "Sign in to your account to continue";
			title: "Welcome Back";
		};
		register: {
			confirmPasswordLabel: "Confirm Password";
			divider: "or";
			emailLabel: "Email";
			googleButton: "Sign up with Google";
			haveAccount: "Already have an account?";
			passwordLabel: "Password";
			signInLink: "Sign in";
			signUpButton: "Create Account";
			subtitle: "Join thousands of creators and marketers";
			title: "Create Your Account";
		};
	};
	index: {
		cta: {
			getStartedFree: "Get Started Free";
			scheduleDemo: "Schedule Demo";
			subtitle: "Join thousands of creators and marketers who've already amplified their social media presence.";
			title: "Ready to Transform Your Social Strategy?";
		};
		features: {
			items: {
				contentLibrary: {
					description: "Access thousands of templates and assets to inspire your next campaign.";
					title: "Content Library";
				};
				deepAnalytics: {
					description: "Understand every metric that matters with beautiful, actionable insights.";
					title: "Deep Analytics";
				};
				growthTracking: {
					description: "Watch your followers grow with real-time performance monitoring.";
					title: "Growth Tracking";
				};
				influencerNetwork: {
					description: "Connect and collaborate with creators across all major platforms.";
					title: "Influencer Network";
				};
				smartScheduling: {
					description: "Post at the perfect time with AI-powered optimal posting time suggestions.";
					title: "Smart Scheduling";
				};
				teamCollaboration: {
					description: "Work together seamlessly with built-in approval workflows and comments.";
					title: "Team Collaboration";
				};
			};
			subtitle: "From scheduling to analytics, we've packed everything into one delightfully easy platform.";
			title: "Everything You Need to Dominate Social";
		};
		footer: {
			brand: "Somemellier";
			copyright: "©{{year}} Somemellier. All rights reserved.";
			links: {
				cookies: "Cookies";
				privacy: "Privacy";
				terms: "Terms";
			};
			sections: {
				company: {
					about: "About";
					blog: "Blog";
					careers: "Careers";
					title: "Company";
				};
				connect: {
					instagram: "Instagram";
					linkedin: "LinkedIn";
					title: "Connect";
					twitter: "Twitter";
				};
				product: {
					features: "Features";
					pricing: "Pricing";
					security: "Security";
					title: "Product";
				};
			};
			tagline: "Your all-in-one social media command center.";
		};
		hero: {
			badge: "Amplify Your Presence";
			dashboardPreview: "Dashboard Preview";
			startFreeTrial: "Start Free Trial";
			stats: {
				posts: {
					label: "Posts Managed";
					number: "50M+";
				};
				rating: {
					label: "User Rating";
					number: "4.9★";
				};
				users: {
					label: "Active Users";
					number: "500K+";
				};
			};
			subtitle: "Manage, analyze, and grow all your social channels from one playful yet powerful platform.";
			title: "Your Social Media Command Center";
			watchDemo: "Watch Demo";
		};
		metadata: {
			description: "Amplify your social media strategy with AI-powered insights and management tools";
			title: "Somemellier - Social Media Marketing Platform";
		};
		nav: {
			brand: "Somemellier";
			features: "Features";
			getStarted: "Get Started";
			pricing: "Pricing";
			signIn: "Sign in";
		};
	};
}

export default Resources;
